/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

public enum Tokens {
   
    Linea,
    Comillas,
    T_dato,
    cadena,
    If,
    Else,
    Do,
    While,
    For,
    Igual,
    Suma,
    Resta,
    Multiplicacion,
    Division,
    Op_logico,
    Op_incremento,
    Op_relacional,
    Op_atribucion,
    Op_booleano,
    Parentesis_a,
    Parentesis_c,
    Llave_a,
    Llave_c,
    Corchete_a,
    Corchete_c,
    Main,
    P_coma,
    coma,
    Identificador,
    Numero,
    ERROR,
    alfabeto,      
    automata,        
    boleano,
    elemento,
    caracter,
    conjunto,
    entero,
    estado,
    expre,
    fin,
    flotante,
    grafico,
    inicio,
    mostrar,
    nuevo,
    funcion,
    validar,
    con,
    afd,
    afn,
    estadofinal,
    estadoinicial,
    hacer,
    hacia,
    mientras,
    er,
    Mostrartabla,
    ordenprincipal
    
}
